# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - xr-messagibg

on:
  push:
    branches:
      - production  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: List NPM scripts
        run: npm run

      # Skip 'npm run build' as you have no build step

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: xr-messagebg       # 👈 your Azure Web App name
          slot-name: production        # or staging if you're using deployment slots
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B13970A649E545C293BE9252353C16B1 }}
